### ISSUE TITLE
Front end console error

### ISSUE THREAD

**Issue by ifrountas** [colorful-tones/acf-slider-block#1]
Hello I just installed the plugin in order to test some things and I noticed it doesn't work on frontend and throwing a console error

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

This happens on the fine swiper-bundle.mjs

**Comment by colorful-tones** [comment]
This is due to server/hosting configuration. What and where are you attempting to test?

If you’re trying to test in Local then you have to modify the Nginx rules for media types. I can drop an example tomorrow when I’m at my desk.

**Comment by colorful-tones** [comment]
If you're using Local the you have to modify the nginx mime types to allow for it `.mjs` files.

`conf/nginx/includes/mime-types.conf.hbs`  and add `mjs` for `application/x-javascript js mjs;`

`.mjs` files are a convention, but not a standard per se.  Node (since v8) has often [alluded to this](https://v8.dev/features/modules#mjs), and even [MDN Docs for Modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#aside_%E2%80%94_.mjs_versus_.js) point to Node's practice. Just something to consider.

The Local team is already aware of this and have it on their roadmap as something to automatically enable in the future.

**Comment by ifrountas** [comment]
ok worked as expected, thank you very much!
